name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
         java-version: 11
        
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
       
      - name: Run unit test
        run: ./gradlew testDebugUnitTest --stacktrace
        
      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v2
        with:
          name: Local Unit Test report
          path: app/build/reports/tests
          if-no-files-found: ignore
  
  build:
    needs: [unit_test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Use Java8
        uses: actions/setup-java@v1
        with:
            java-version: 11

      - name: Build debug apk
        run: ./gradlew clean assembleDebug --stacktrace

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: Debug APK
          path: app/build/outputs/apk/debug/app-debug.apk
